### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by werediver** [blamario/language-dart#1]
For the sake of keeping strangers informed 🙂

This fork adds quite some fixes and improvements on top of the now unmaintained [original repo](https://github.com/kseo/language-dart).

As [mentioned](https://github.com/kseo/language-dart/issues/2#issuecomment-517263200) by the owner of the fork @blamario:

> As for the Dart version, it's at an indeterminate version between the root repo and 2.2. That's because I tried to follow the current standrd at the time, but I didn't want to modify the AST too far.

At the same time, there exists a bigger ongoing work, [mentioned](https://github.com/kseo/language-dart/issues/2#issuecomment-517273188) by @sigrlami:

> I have a closed fork with many more corrections that also contains code from @blamario. I believe best course of action here gain maintainership rights and start publishing. My aim is upstream as I use this package for my flutter bindings I plan to release this autumn.

@blamario Please, feel free to close this ticket, if you prefer.

**Comment by blamario** [comment]
So what's the plan, now that we have write access to kseo/language-dart? Should I merge this fork or leave that to @sigrlami?

**Comment by werediver** [comment]
@blamario Just merging your work into the original repo would already be an improvement, but I'd consider aligning with @sigrlami whether this would later complicate merging his work in (if his work is strictly on top of yours, it's good; otherwise it depends).

**Comment by sigrlami** [comment]
@blamario I'll check your PR in upstream over the weekend. If it's not much work that allow transfer of my private code I most probably will merge it and will continue adding features in upstream.

**Comment by sigrlami** [comment]
@werediver upstream access gained. Work started, you may close this issue.
